### ISSUE TITLE
Size(s) of the font

### ISSUE THREAD

**Issue by dumblob** [ultlang/ultlf#4]
Could you list somewhere the currently_supported and otherwise recommended font sizes?

**Comment by ultlang** [comment]
hi,
there's only one size so far and i don't plan on making more. i'm not sure what measurement is considered the font size, but the x-height is 5 px, the cap and ascender heights are 7 px and the descenders go down 2px (usually. some glyphs have different sized ascenders/descenders). hope this helps

**Comment by dumblob** [comment]
Thanks!

Btw. do you plan some support for asian languages? I know it's basically impossible to squeeze it into 5x7 px but maybe some ligatures or such could help...
